files = [
  "AddServiceCharge"
  "AddHourlyEmployee"
  "MemoryDB"
  "HourlyClassification"
  "WeeklySchedule"
  "HoldMethod"
  "Employee"
  "AddCommissionedEmployee"
  "CommissionedClassification"
  "BiWeeklySchedule"
  "MonthlySchedule"
  "AddSalariedEmployee"
  "SalariedClassification"
  "AddSalesReceipt"
  "SalesReceipt"
  "TimeCard"
  "AddTimeCard"
  "ChangeAddress"
  "ChangeCommissioned"
  "ChangeHourly"
  "ChangeName"
  "ChangeSalaried"
  "DeleteEmployee"
  "ChangeUnionMember"
  "UnionAffiliation"
  "ChangeUnaffiliated"
  "NoAffiliation"
  "ServiceCharge"
  "AddEmployeePresenter"
  "Payday"
  "Paycheck"
]

for file in files
  module.exports[file] = require "./#{file}"

